export const FETCH_DATA_NEXT_LAUNCH = 'FETCH_DATA_NEXT_LAUNCH';

export const FETCH_DATA_PAST_LAUNCHES = 'FETCH_DATA_PAST_LAUNCHES';
export const FETCH_DATA_UPCOMING_LAUNCHES = 'FETCH_DATA_UPCOMING_LAUNCHES';

export const FETCH_DATA_ALL_ROCKETS = 'FETCH_DATA_ALL_ROCKETS';

export const FETCH_DATA_ONE_MISSOIN = 'FETCH_DATA_ONE_MISSOIN';